"""edit_outbox

Revision ID: 1028c53f7d65
Revises: aa9ac53bb490
Create Date: 2026-10-05 21:49:38.398370

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1028c53f7d65"
down_revision: str | Sequence[str] | None = "aa9ac53bb490"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post_outboxes",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "post_outboxes",
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "post_outboxes",
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "post_outboxes", sa.Column("retry_count", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "post_outboxes",
        "status",
        existing_type=sa.VARCHAR(length=11),
        type_=sa.Enum(
            "pending", "completed", "failed", name="outboxstatus", native_enum=False
        ),
        existing_nullable=False,
    )
    op.create_index(
        "ix_outbox_status_next_attempt",
        "post_outboxes",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_post_outboxes_status"), "post_outboxes", ["status"], unique=False
    )
    op.drop_column("post_outboxes", "updated_at")
    op.drop_column("post_outboxes", "created_date")
    op.create_index(op.f("ix_posts_rubrics"), "posts", ["rubrics"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_rubrics"), table_name="posts")
    op.add_column(
        "post_outboxes",
        sa.Column(
            "created_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "post_outboxes",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_post_outboxes_status"), table_name="post_outboxes")
    op.drop_index("ix_outbox_status_next_attempt", table_name="post_outboxes")
    op.alter_column(
        "post_outboxes",
        "status",
        existing_type=sa.Enum(
            "pending", "completed", "failed", name="outboxstatus", native_enum=False
        ),
        type_=sa.VARCHAR(length=11),
        existing_nullable=False,
    )
    op.drop_column("post_outboxes", "retry_count")
    op.drop_column("post_outboxes", "processed_at")
    op.drop_column("post_outboxes", "next_attempt_at")
    op.drop_column("post_outboxes", "created_at")
    # ### end Alembic commands ###
