"""add outbox

Revision ID: aa9ac53bb490
Revises: 48d8698ffa4e
Create Date: 2026-10-03 18:10:52.981935

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aa9ac53bb490"
down_revision: str | Sequence[str] | None = "48d8698ffa4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_outboxes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                name="outboxstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "create", "update", "delete", name="outboxaction", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_post_outboxes_id"), "post_outboxes", ["id"], unique=False)
    op.add_column(
        "posts", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.alter_column(
        "posts",
        "created_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "posts",
        "created_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("posts", "updated_at")
    op.drop_index(op.f("ix_post_outboxes_id"), table_name="post_outboxes")
    op.drop_table("post_outboxes")
    # ### end Alembic commands ###
